package ca.ulaval.glo2004.patio;

public enum ValidationErrorType {
    POST_HEIGHT,
    POST_DIMENSIONS,
    SPAN_LENGTH,
    JOIST_SPACING,
    COVERING_DIMENSIONS,
    JOIST_DIMENSIONS,
    CANTILEVER_LENGTH,
    POST_SPACING,
    PLIES_PER_BEAM_SINGLE_SPAN,
    PLIES_PER_BEAM_TWO_SPANS,
    BEAM_DIMENSIONS_SINGLE_SPAN,
    BEAM_DIMENSIONS_TWO_SPANS,
    OPTIMAL_PATIO_CONFIGURATION,
}
